### PR TITLE
Added some infos to KNX

### PR DESCRIPTION
**Pull request by f0rw4rd**
Hi ! 

I added some infos to the KNX page and thx for the cool work !

### CODE REVIEW

**Comment by f0rw4rd** [comment]
Ah, I just saw the db format. Will try to merge the KNX infos into the db !  Closing the PR

**Comment by claire-lex** [comment]
Hello, no problem! You can also leave it this way and I will add the content to the db

**Comment by claire-lex** [comment]
Thank you for the PR! The content you submitted has been merged and added to the database as discussed. As the pages are generated automatically, so you will notice some differences between your submission and the final pages that include it.

**Comment by f0rw4rd** [comment]
Thanks !

**Pull request merged**
